# signup
POST http://localhost:3000/user/auth/signup
Content-Type: application/json

{
    "email":"test@example.com",
    "password":"password"
}

###

# signin
POST http://localhost:3000/user/auth/signin
Content-Type: application/json

{
    "email":"test@example.com",
    "password":"password"
}

###

# signout
POST http://localhost:3000/user/auth/signout

###

# find user
GET http://localhost:3000/user

###

# create habit
POST http://localhost:3000/habits
Content-Type: application/json

{
    "title": "Habit 2",
    "description": "Description 2",
    "frequencyType": "custom",
    "customDays": ["monday", "wednesday", "friday"],
    "reminderTimes": ["08:00", "12:00"],
    "isActive": true
}

###

# get all habits
GET http://localhost:3000/habits

###

# get habit by id
GET http://localhost:3000/habits/130e2069-8342-4249-8975-635ade1c1609

###

# update habit
PATCH http://localhost:3000/habits/130e2069-8342-4249-8975-635ade1c1609
Content-Type: application/json

{
    "title": "Habit 1",
    "description": "Description 1",
    "frequencyType": "daily",
    "intervalDays": 4,
    "customDays": ["monday", "wednesday", "friday"],
    "reminderTimes": ["08:00", "12:00", "18:00"],
    "isActive": true
}

###

# delete habit
DELETE http://localhost:3000/habits/24f3e7c9-a4ae-4566-9ea6-8834ef130761

###

# complete habit
POST http://localhost:3000/habits/130e2069-8342-4249-8975-635ade1c1609/completed

###

# get habit logs
GET http://localhost:3000/habits/130e2069-8342-4249-8975-635ade1c1609/logs

###

# get analytics summary
# GET http://localhost:3000/analytics/summary

###

# get streak
GET http://localhost:3000/streak

###

# get all streaks
GET http://localhost:3000/streak/all

###

# get streak by habit id
GET http://localhost:3000/streak/130e2069-8342-4249-8975-635ade1c1609